# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_databases.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_databases(object):
    def setupUi(self, Dialog_add_databases):
        Dialog_add_databases.setObjectName("Dialog_add_databases")
        Dialog_add_databases.resize(280, 82)
        self.comboBox_databases = QtWidgets.QComboBox(Dialog_add_databases)
        self.comboBox_databases.setGeometry(QtCore.QRect(10, 10, 256, 20))
        self.comboBox_databases.setObjectName("comboBox_databases")
        self.pushButton_guardar_base_indexadas = QtWidgets.QPushButton(Dialog_add_databases)
        self.pushButton_guardar_base_indexadas.setGeometry(QtCore.QRect(190, 40, 75, 23))
        self.pushButton_guardar_base_indexadas.setObjectName("pushButton_guardar_base_indexadas")

        self.retranslateUi(Dialog_add_databases)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add_databases)

    def retranslateUi(self, Dialog_add_databases):
        _translate = QtCore.QCoreApplication.translate
        Dialog_add_databases.setWindowTitle(_translate("Dialog_add_databases", "Agregar base de datos indexada"))
        self.pushButton_guardar_base_indexadas.setText(_translate("Dialog_add_databases", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_add_databases = QtWidgets.QDialog()
    ui = Ui_Dialog_add_databases()
    ui.setupUi(Dialog_add_databases)
    Dialog_add_databases.show()
    sys.exit(app.exec_())
