# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_author.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_author(object):
    def setupUi(self, Dialog_add_author):
        Dialog_add_author.setObjectName("Dialog_add_author")
        Dialog_add_author.resize(338, 193)
        self.pushButton_guardar_autor = QtWidgets.QPushButton(Dialog_add_author)
        self.pushButton_guardar_autor.setGeometry(QtCore.QRect(250, 20, 75, 23))
        self.pushButton_guardar_autor.setObjectName("pushButton_guardar_autor")
        self.layoutWidget = QtWidgets.QWidget(Dialog_add_author)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 211, 145))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_nombres = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_nombres.setObjectName("lineEdit_nombres")
        self.gridLayout.addWidget(self.lineEdit_nombres, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_apellidos = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_apellidos.setObjectName("lineEdit_apellidos")
        self.gridLayout.addWidget(self.lineEdit_apellidos, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.checkBox_fem = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_fem.setObjectName("checkBox_fem")
        self.gridLayout.addWidget(self.checkBox_fem, 2, 1, 1, 1)
        self.checkBox_masc = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_masc.setObjectName("checkBox_masc")
        self.gridLayout.addWidget(self.checkBox_masc, 3, 1, 1, 1)
        self.checkBox_otro = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_otro.setObjectName("checkBox_otro")
        self.gridLayout.addWidget(self.checkBox_otro, 4, 1, 1, 1)
        self.lineEdit_genero = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_genero.setObjectName("lineEdit_genero")
        self.gridLayout.addWidget(self.lineEdit_genero, 5, 1, 1, 1)

        self.retranslateUi(Dialog_add_author)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add_author)

    def retranslateUi(self, Dialog_add_author):
        _translate = QtCore.QCoreApplication.translate
        Dialog_add_author.setWindowTitle(_translate("Dialog_add_author", "Agregar Autor"))
        self.pushButton_guardar_autor.setText(_translate("Dialog_add_author", "Agregar"))
        self.label_2.setText(_translate("Dialog_add_author", "Nombres:"))
        self.label_3.setText(_translate("Dialog_add_author", "Apellidos:"))
        self.label_4.setText(_translate("Dialog_add_author", "Género:"))
        self.checkBox_fem.setText(_translate("Dialog_add_author", "Femenino"))
        self.checkBox_masc.setText(_translate("Dialog_add_author", "Masculino"))
        self.checkBox_otro.setText(_translate("Dialog_add_author", "Otro:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_add_author = QtWidgets.QDialog()
    ui = Ui_Dialog_add_author()
    ui.setupUi(Dialog_add_author)
    Dialog_add_author.show()
    sys.exit(app.exec_())
