# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.resize(452, 342)
        Dialog_Login.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.layoutWidget = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 2, 357, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 2, 1, 1, 1)
        self.toolButton_new_user = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_new_user.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolButton_new_user.setObjectName("toolButton_new_user")
        self.gridLayout.addWidget(self.toolButton_new_user, 4, 0, 1, 1)
        self.label_fecha_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_fecha_30.setFont(font)
        self.label_fecha_30.setAcceptDrops(False)
        self.label_fecha_30.setAutoFillBackground(False)
        self.label_fecha_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_fecha_30.setScaledContents(False)
        self.label_fecha_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fecha_30.setWordWrap(True)
        self.label_fecha_30.setObjectName("label_fecha_30")
        self.gridLayout.addWidget(self.label_fecha_30, 0, 0, 1, 2)
        self.pushButton_cancel_login = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel_login.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_cancel_login.setObjectName("pushButton_cancel_login")
        self.gridLayout.addWidget(self.pushButton_cancel_login, 3, 0, 1, 1)
        self.toolButton_recover_password = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_recover_password.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolButton_recover_password.setObjectName("toolButton_recover_password")
        self.gridLayout.addWidget(self.toolButton_recover_password, 4, 1, 1, 1)
        self.label_fecha_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_2.setFont(font)
        self.label_fecha_2.setObjectName("label_fecha_2")
        self.gridLayout.addWidget(self.label_fecha_2, 2, 0, 1, 1)
        self.label_fecha = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha.setFont(font)
        self.label_fecha.setObjectName("label_fecha")
        self.gridLayout.addWidget(self.label_fecha, 1, 0, 1, 1)
        self.pushButton_Login = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Login.setDefault(True)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.gridLayout.addWidget(self.pushButton_Login, 3, 1, 1, 1)
        self.comboBox_login_users = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_login_users.setObjectName("comboBox_login_users")
        self.gridLayout.addWidget(self.comboBox_login_users, 1, 1, 1, 1)

        self.retranslateUi(Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "Login"))
        self.toolButton_new_user.setText(_translate("Dialog_Login", "Crear usuario"))
        self.label_fecha_30.setText(_translate("Dialog_Login", "Sistema de Ingreso de Datos"))
        self.pushButton_cancel_login.setText(_translate("Dialog_Login", "Cancel"))
        self.toolButton_recover_password.setText(_translate("Dialog_Login", "Recuperar contraseña"))
        self.label_fecha_2.setText(_translate("Dialog_Login", "Contraseña:"))
        self.label_fecha.setText(_translate("Dialog_Login", "Usuario:"))
        self.pushButton_Login.setText(_translate("Dialog_Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Login = QtWidgets.QDialog()
    ui = Ui_Dialog_Login()
    ui.setupUi(Dialog_Login)
    Dialog_Login.show()
    sys.exit(app.exec_())
