# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recover_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_recover_password(object):
    def setupUi(self, Dialog_recover_password):
        Dialog_recover_password.setObjectName("Dialog_recover_password")
        Dialog_recover_password.resize(400, 339)
        Dialog_recover_password.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.layoutWidget = QtWidgets.QWidget(Dialog_recover_password)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 350, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_fecha_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_fecha_30.setFont(font)
        self.label_fecha_30.setAcceptDrops(False)
        self.label_fecha_30.setAutoFillBackground(False)
        self.label_fecha_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_fecha_30.setScaledContents(False)
        self.label_fecha_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fecha_30.setWordWrap(True)
        self.label_fecha_30.setObjectName("label_fecha_30")
        self.gridLayout.addWidget(self.label_fecha_30, 0, 0, 1, 2)
        self.pushButton_cancel_recover = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel_recover.setObjectName("pushButton_cancel_recover")
        self.gridLayout.addWidget(self.pushButton_cancel_recover, 4, 0, 1, 1)
        self.pushButton_Ok_recover = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Ok_recover.setObjectName("pushButton_Ok_recover")
        self.gridLayout.addWidget(self.pushButton_Ok_recover, 4, 1, 1, 1)
        self.label_fecha_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_4.setFont(font)
        self.label_fecha_4.setObjectName("label_fecha_4")
        self.gridLayout.addWidget(self.label_fecha_4, 2, 0, 1, 1)
        self.label_fecha = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha.setFont(font)
        self.label_fecha.setObjectName("label_fecha")
        self.gridLayout.addWidget(self.label_fecha, 1, 0, 1, 1)
        self.comboBox_recover_users = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_recover_users.setObjectName("comboBox_recover_users")
        self.gridLayout.addWidget(self.comboBox_recover_users, 1, 1, 1, 1)
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.gridLayout.addWidget(self.lineEdit_new_password, 2, 1, 1, 1)
        self.label_fecha_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_3.setFont(font)
        self.label_fecha_3.setObjectName("label_fecha_3")
        self.gridLayout.addWidget(self.label_fecha_3, 3, 0, 1, 1)
        self.lineEdit_new_password_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_new_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new_password_2.setObjectName("lineEdit_new_password_2")
        self.gridLayout.addWidget(self.lineEdit_new_password_2, 3, 1, 1, 1)

        self.retranslateUi(Dialog_recover_password)
        QtCore.QMetaObject.connectSlotsByName(Dialog_recover_password)

    def retranslateUi(self, Dialog_recover_password):
        _translate = QtCore.QCoreApplication.translate
        Dialog_recover_password.setWindowTitle(_translate("Dialog_recover_password", "Recuperar contraseña"))
        self.label_fecha_30.setText(_translate("Dialog_recover_password", "Recuperar contraseña"))
        self.pushButton_cancel_recover.setText(_translate("Dialog_recover_password", "Cancel"))
        self.pushButton_Ok_recover.setText(_translate("Dialog_recover_password", "OK"))
        self.label_fecha_4.setText(_translate("Dialog_recover_password", "Nueva contraseña:"))
        self.label_fecha.setText(_translate("Dialog_recover_password", "Usuario:"))
        self.label_fecha_3.setText(_translate("Dialog_recover_password", "Repetir contraseña:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_recover_password = QtWidgets.QDialog()
    ui = Ui_Dialog_recover_password()
    ui.setupUi(Dialog_recover_password)
    Dialog_recover_password.show()
    sys.exit(app.exec_())
