# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_new_user(object):
    def setupUi(self, Dialog_new_user):
        Dialog_new_user.setObjectName("Dialog_new_user")
        Dialog_new_user.resize(400, 340)
        Dialog_new_user.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"\n"
"")
        self.widget = QtWidgets.QWidget(Dialog_new_user)
        self.widget.setGeometry(QtCore.QRect(30, 10, 350, 311))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_fecha_30 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_fecha_30.setFont(font)
        self.label_fecha_30.setAcceptDrops(False)
        self.label_fecha_30.setAutoFillBackground(False)
        self.label_fecha_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_fecha_30.setScaledContents(False)
        self.label_fecha_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fecha_30.setWordWrap(True)
        self.label_fecha_30.setObjectName("label_fecha_30")
        self.gridLayout.addWidget(self.label_fecha_30, 0, 0, 1, 4)
        self.label_fecha = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha.setFont(font)
        self.label_fecha.setObjectName("label_fecha")
        self.gridLayout.addWidget(self.label_fecha, 1, 0, 1, 1)
        self.lineEdit_new_username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_new_username.setObjectName("lineEdit_new_username")
        self.gridLayout.addWidget(self.lineEdit_new_username, 1, 1, 1, 3)
        self.label_fecha_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_2.setFont(font)
        self.label_fecha_2.setObjectName("label_fecha_2")
        self.gridLayout.addWidget(self.label_fecha_2, 2, 0, 1, 1)
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.gridLayout.addWidget(self.lineEdit_new_password, 2, 1, 1, 3)
        self.label_fecha_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_3.setFont(font)
        self.label_fecha_3.setObjectName("label_fecha_3")
        self.gridLayout.addWidget(self.label_fecha_3, 3, 0, 1, 3)
        self.lineEdit_new_password_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_new_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_new_password_2.setObjectName("lineEdit_new_password_2")
        self.gridLayout.addWidget(self.lineEdit_new_password_2, 3, 3, 1, 1)
        self.label_fecha_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_4.setFont(font)
        self.label_fecha_4.setObjectName("label_fecha_4")
        self.gridLayout.addWidget(self.label_fecha_4, 4, 0, 1, 2)
        self.lineEdit_new_email = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_new_email.setObjectName("lineEdit_new_email")
        self.gridLayout.addWidget(self.lineEdit_new_email, 4, 2, 1, 2)
        self.label_fecha_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_5.setFont(font)
        self.label_fecha_5.setObjectName("label_fecha_5")
        self.gridLayout.addWidget(self.label_fecha_5, 5, 0, 1, 2)
        self.lineEdit_new_email_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_new_email_2.setObjectName("lineEdit_new_email_2")
        self.gridLayout.addWidget(self.lineEdit_new_email_2, 5, 2, 1, 2)
        self.pushButton_cancel_newuser = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel_newuser.setObjectName("pushButton_cancel_newuser")
        self.gridLayout.addWidget(self.pushButton_cancel_newuser, 6, 0, 1, 2)
        self.pushButton_Ok_newuser = QtWidgets.QPushButton(self.widget)
        self.pushButton_Ok_newuser.setObjectName("pushButton_Ok_newuser")
        self.gridLayout.addWidget(self.pushButton_Ok_newuser, 6, 2, 1, 2)

        self.retranslateUi(Dialog_new_user)
        QtCore.QMetaObject.connectSlotsByName(Dialog_new_user)

    def retranslateUi(self, Dialog_new_user):
        _translate = QtCore.QCoreApplication.translate
        Dialog_new_user.setWindowTitle(_translate("Dialog_new_user", "Crear Usuario"))
        self.label_fecha_30.setText(_translate("Dialog_new_user", "Crear usuario"))
        self.label_fecha.setText(_translate("Dialog_new_user", "Usuario:"))
        self.label_fecha_2.setText(_translate("Dialog_new_user", "Contraseña:"))
        self.label_fecha_3.setText(_translate("Dialog_new_user", "Repetir contraseña:"))
        self.label_fecha_4.setText(_translate("Dialog_new_user", "Correo:"))
        self.label_fecha_5.setText(_translate("Dialog_new_user", "Repetir correo:"))
        self.pushButton_cancel_newuser.setText(_translate("Dialog_new_user", "Cancel"))
        self.pushButton_Ok_newuser.setText(_translate("Dialog_new_user", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_new_user = QtWidgets.QDialog()
    ui = Ui_Dialog_new_user()
    ui.setupUi(Dialog_new_user)
    Dialog_new_user.show()
    sys.exit(app.exec_())
