# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pub_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_pub_search(object):
    def setupUi(self, MainWindow_pub_search):
        MainWindow_pub_search.setObjectName("MainWindow_pub_search")
        MainWindow_pub_search.resize(875, 628)
        MainWindow_pub_search.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 1px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow_pub_search)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_keywords = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_keywords.setFont(font)
        self.checkBox_keywords.setObjectName("checkBox_keywords")
        self.gridLayout.addWidget(self.checkBox_keywords, 1, 0, 1, 1)
        self.lineEdit_keywords = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_keywords.setText("")
        self.lineEdit_keywords.setPlaceholderText("")
        self.lineEdit_keywords.setObjectName("lineEdit_keywords")
        self.gridLayout.addWidget(self.lineEdit_keywords, 1, 1, 1, 1)
        self.checkBox_category = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_category.setFont(font)
        self.checkBox_category.setObjectName("checkBox_category")
        self.gridLayout.addWidget(self.checkBox_category, 1, 2, 1, 1)
        self.comboBox_category_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_category_search.setObjectName("comboBox_category_search")
        self.gridLayout.addWidget(self.comboBox_category_search, 1, 3, 1, 1)
        self.checkBox_year = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_year.setFont(font)
        self.checkBox_year.setObjectName("checkBox_year")
        self.gridLayout.addWidget(self.checkBox_year, 2, 0, 1, 1)
        self.dateEdit_year = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_year.setCalendarPopup(True)
        self.dateEdit_year.setObjectName("dateEdit_year")
        self.gridLayout.addWidget(self.dateEdit_year, 2, 1, 1, 1)
        self.checkBox_area = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_area.setFont(font)
        self.checkBox_area.setObjectName("checkBox_area")
        self.gridLayout.addWidget(self.checkBox_area, 2, 2, 1, 1)
        self.comboBox_area_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_area_search.setObjectName("comboBox_area_search")
        self.gridLayout.addWidget(self.comboBox_area_search, 2, 3, 1, 1)
        self.checkBox_type = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_type.setFont(font)
        self.checkBox_type.setObjectName("checkBox_type")
        self.gridLayout.addWidget(self.checkBox_type, 3, 0, 1, 1)
        self.comboBox_type_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_type_search.setObjectName("comboBox_type_search")
        self.gridLayout.addWidget(self.comboBox_type_search, 3, 1, 1, 1)
        self.checkBox_author = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_author.setFont(font)
        self.checkBox_author.setObjectName("checkBox_author")
        self.gridLayout.addWidget(self.checkBox_author, 3, 2, 1, 1)
        self.lineEdit_author_search = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_author_search.setText("")
        self.lineEdit_author_search.setObjectName("lineEdit_author_search")
        self.gridLayout.addWidget(self.lineEdit_author_search, 3, 3, 1, 1)
        self.checkBox_journal = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_journal.setFont(font)
        self.checkBox_journal.setObjectName("checkBox_journal")
        self.gridLayout.addWidget(self.checkBox_journal, 4, 0, 1, 1)
        self.comboBox_journal_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_journal_search.setObjectName("comboBox_journal_search")
        self.gridLayout.addWidget(self.comboBox_journal_search, 4, 1, 1, 1)
        self.checkBox_pub_state = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_pub_state.setFont(font)
        self.checkBox_pub_state.setObjectName("checkBox_pub_state")
        self.gridLayout.addWidget(self.checkBox_pub_state, 4, 2, 1, 1)
        self.comboBox_pub_state_search = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_pub_state_search.setObjectName("comboBox_pub_state_search")
        self.gridLayout.addWidget(self.comboBox_pub_state_search, 4, 3, 1, 1)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 5, 3, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setFrameShape(QtWidgets.QFrame.Box)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 6, 0, 1, 4)
        self.pushButton_export = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout.addWidget(self.pushButton_export, 7, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow_pub_search.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_pub_search)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_pub_search.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_pub_search)
        self.statusbar.setObjectName("statusbar")
        MainWindow_pub_search.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_pub_search)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_pub_search)

    def retranslateUi(self, MainWindow_pub_search):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_pub_search.setWindowTitle(_translate("MainWindow_pub_search", "Busqueda de Publicaciones"))
        self.checkBox_keywords.setText(_translate("MainWindow_pub_search", "Palabras clave:"))
        self.checkBox_category.setText(_translate("MainWindow_pub_search", "Categoría:"))
        self.checkBox_year.setText(_translate("MainWindow_pub_search", "Año de publicación:"))
        self.dateEdit_year.setDisplayFormat(_translate("MainWindow_pub_search", "yyyy"))
        self.checkBox_area.setText(_translate("MainWindow_pub_search", "Área de salud:"))
        self.checkBox_type.setText(_translate("MainWindow_pub_search", "Tipo de publicación:"))
        self.checkBox_author.setText(_translate("MainWindow_pub_search", "Autor:"))
        self.checkBox_journal.setText(_translate("MainWindow_pub_search", "Revista:"))
        self.checkBox_pub_state.setText(_translate("MainWindow_pub_search", "Estado de publicación:"))
        self.pushButton_search.setText(_translate("MainWindow_pub_search", "Buscar"))
        self.pushButton_export.setText(_translate("MainWindow_pub_search", "Exportar"))
        self.label_2.setText(_translate("MainWindow_pub_search", "Búsqueda de publicaciones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_pub_search = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_pub_search()
    ui.setupUi(MainWindow_pub_search)
    MainWindow_pub_search.show()
    sys.exit(app.exec_())
