# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remove_authors.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_remove_author(object):
    def setupUi(self, Dialog_remove_author):
        Dialog_remove_author.setObjectName("Dialog_remove_author")
        Dialog_remove_author.resize(280, 104)
        Dialog_remove_author.setStyleSheet("QWidget {\n"
"  background-color: #fff;\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  border-radius: 8px;\n"
"  border: 1px solid #e0e4e7;\n"
"  padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}\n"
"QPushButton {\n"
"  background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #0d6efd;\n"
"  padding: 10px 10px;\n"
"  margin-top: 1px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #0b5ed7;\n"
"  border: 1px solid #9ac3fe;\n"
"}\n"
"QMenu {\n"
"background-color: #fff;\n"
"border: 1px solid black;\n"
"margin: 2px;\n"
"}\n"
"QMenu::item {\n"
"background-color: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"background-color: #0b5ed7;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_remove_author)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_authors = QtWidgets.QComboBox(Dialog_remove_author)
        self.comboBox_authors.setObjectName("comboBox_authors")
        self.gridLayout.addWidget(self.comboBox_authors, 0, 0, 1, 2)
        self.pushButton_remove_author = QtWidgets.QPushButton(Dialog_remove_author)
        self.pushButton_remove_author.setObjectName("pushButton_remove_author")
        self.gridLayout.addWidget(self.pushButton_remove_author, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog_remove_author)
        QtCore.QMetaObject.connectSlotsByName(Dialog_remove_author)

    def retranslateUi(self, Dialog_remove_author):
        _translate = QtCore.QCoreApplication.translate
        Dialog_remove_author.setWindowTitle(_translate("Dialog_remove_author", "Eliminar autor"))
        self.pushButton_remove_author.setText(_translate("Dialog_remove_author", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_remove_author = QtWidgets.QDialog()
    ui = Ui_Dialog_remove_author()
    ui.setupUi(Dialog_remove_author)
    Dialog_remove_author.show()
    sys.exit(app.exec_())
